# Makefile — Diamond exokernel
#
# Source layout:
#   arch/x86/        x86-specific: CPU, I/O, spinlock, PCI, SMP
#   drivers/         hardware drivers: terminal, serial, keyboard, font
#   drivers/net/     NIC drivers + generic probe loop
#   drivers/video/   video drivers (BGA, VirtIO GPU, Limine fallback)
#   drivers/audio/   audio drivers (HDA, AC97, PC speaker)
#   apps/shell/      interactive shell demo application
#   kernel/          boot entry point (main.c) + linker script
#
# Targets: all, iso, run [NIC=<device>], clean
#
# NIC selection for 'make run' (default: e1000):
#   make run NIC=e1000
#   make run NIC=e1000e
#   make run NIC=virtio-net-pci
#   make run NIC=rtl8139
#   make run NIC=pcnet
#   make run NIC=ne2k_pci

# ── Toolchain ─────────────────────────────────────────────────────────────────
CC      := gcc
LD      := ld
AS      := nasm
OBJCOPY := objcopy

GCC_INC := $(shell $(CC) -print-file-name=include)

# ── Paths ─────────────────────────────────────────────────────────────────────
LIMINE_DIR  := third_party/limine
FONTS_DIR   := third_party/fonts
STB_DIR     := third_party/stb
BUILD       := build
ISO_ROOT    := $(BUILD)/iso_root
KERNEL_ELF  := $(BUILD)/kernel.elf
ISO         := diamond.iso

FONT_TTF    := $(FONTS_DIR)/JetBrainsMono-Regular.ttf

# iwlwifi firmware blob for Intel Wi-Fi 6 AX201 (Surface Laptop 3 CNVi radio).
# Extract with tools/iwl_diag.sh and place in third_party/firmware/.  If the
# file is absent the build still succeeds (OBJ_IWL_FW becomes an empty blob
# and the driver reports "no firmware").
IWL_FW_BIN  := third_party/firmware/iwlwifi-Qu-c0-hr-b0-77.ucode

# ── Compiler flags ────────────────────────────────────────────────────────────
KFLAGS := \
    -std=c99 \
    -ffreestanding \
    -fno-stack-protector \
    -fno-pie -fno-pic \
    -mno-red-zone \
    -mcmodel=kernel \
    -m64 \
    -nostdlib -nostdinc \
    -isystem $(GCC_INC) \
    -I$(LIMINE_DIR) \
    -Wall -Wextra \
    -O2

# Extra flags for font.c (stb_truetype generates many warnings)
FONT_EXTRA := \
    -Wno-unused-function \
    -Wno-unused-parameter \
    -Wno-missing-field-initializers \
    -Wno-sign-compare \
    -Wno-type-limits \
    -Wno-unused-but-set-variable \
    -Wno-implicit-fallthrough

# ── Linker flags ──────────────────────────────────────────────────────────────
LDFLAGS := \
    -T kernel/linker.ld \
    -nostdlib \
    -static \
    -m elf_x86_64 \
    -z max-page-size=0x1000 \
    -z noexecstack \
    --no-dynamic-linker

# ── Object files ──────────────────────────────────────────────────────────────
OBJ_MAIN      := $(BUILD)/main.o
OBJ_ALLOC     := $(BUILD)/alloc.o
OBJ_FONT      := $(BUILD)/font.o
OBJ_FONT_TTF  := $(BUILD)/jetbrains_mono.o
OBJ_SERIAL    := $(BUILD)/serial.o
OBJ_KEYBOARD  := $(BUILD)/keyboard.o
OBJ_TERMINAL  := $(BUILD)/terminal.o
OBJ_SHELL     := $(BUILD)/shell.o
OBJ_RAYTRACE  := $(BUILD)/raytrace.o
OBJ_SMP       := $(BUILD)/smp.o
OBJ_PCI       := $(BUILD)/pci.o
OBJ_VM        := $(BUILD)/vm.o
OBJ_NET       := $(BUILD)/net.o
OBJ_E1000     := $(BUILD)/e1000.o
OBJ_E1000E    := $(BUILD)/e1000e.o
OBJ_VIRTIO    := $(BUILD)/virtio_net.o
OBJ_RTL8139   := $(BUILD)/rtl8139.o
OBJ_PCNET     := $(BUILD)/pcnet.o
OBJ_NE2K      := $(BUILD)/ne2k.o
OBJ_IWLWIFI   := $(BUILD)/iwlwifi.o
OBJ_IWL_FW_LDR := $(BUILD)/iwl_fw.o
OBJ_IWL_FW_BOOT := $(BUILD)/iwl_fw_load.o
OBJ_IWL_CMD     := $(BUILD)/iwl_cmd.o
OBJ_ARP       := $(BUILD)/arp.o
OBJ_IPV4      := $(BUILD)/ipv4.o
OBJ_DHCP      := $(BUILD)/dhcp.o
OBJ_TCP       := $(BUILD)/tcp.o
OBJ_HTTP      := $(BUILD)/http.o
OBJ_VIDEO     := $(BUILD)/video.o
OBJ_BGA       := $(BUILD)/bga.o
OBJ_VGPU      := $(BUILD)/virtio_gpu.o
OBJ_LIMINEFB  := $(BUILD)/limine_fb.o
OBJ_AUDIO     := $(BUILD)/audio.o
OBJ_HDA       := $(BUILD)/hda.o
OBJ_AC97      := $(BUILD)/ac97.o
OBJ_PCSPK     := $(BUILD)/pcspk.o
OBJ_MOUSE          := $(BUILD)/mouse.o
OBJ_VIRTIO_INPUT   := $(BUILD)/virtio_input.o
OBJ_PIANO          := $(BUILD)/piano.o
OBJ_SAM            := $(BUILD)/sam.o

# ── Piano samples (generated by tools/gen_samples at build time) ──────────
SAMPLE_NAMES := A1 A2 A3 A4 A5 A6
SAMPLE_RAWS  := $(patsubst %,samples/piano_%.raw,$(SAMPLE_NAMES))
SAMPLE_OBJS  := $(patsubst %,$(BUILD)/sample_piano_%.o,$(SAMPLE_NAMES))

OBJS := \
    $(OBJ_MAIN) $(OBJ_ALLOC) \
    $(OBJ_FONT) $(OBJ_FONT_TTF) \
    $(OBJ_SERIAL) $(OBJ_KEYBOARD) $(OBJ_MOUSE) $(OBJ_VIRTIO_INPUT) $(OBJ_SAM) $(OBJ_TERMINAL) \
    $(OBJ_SHELL) $(OBJ_RAYTRACE) $(OBJ_PIANO) \
    $(OBJ_SMP) $(OBJ_PCI) $(OBJ_VM) \
    $(OBJ_NET) $(OBJ_E1000) $(OBJ_E1000E) \
    $(OBJ_VIRTIO) $(OBJ_RTL8139) $(OBJ_PCNET) $(OBJ_NE2K) \
    $(OBJ_IWLWIFI) $(OBJ_IWL_FW_LDR) $(OBJ_IWL_FW_BOOT) $(OBJ_IWL_CMD) \
    $(OBJ_ARP) $(OBJ_IPV4) $(OBJ_DHCP) $(OBJ_TCP) $(OBJ_HTTP) \
    $(OBJ_VIDEO) $(OBJ_BGA) $(OBJ_VGPU) $(OBJ_LIMINEFB) \
    $(OBJ_AUDIO) $(OBJ_HDA) $(OBJ_AC97) $(OBJ_PCSPK) \
    $(SAMPLE_OBJS)

# ─────────────────────────────────────────────────────────────────────────────
.PHONY: all iso run run-spice install efi-register clean

all: iso

# ── kernel entry + allocator ──────────────────────────────────────────────────
$(OBJ_MAIN): kernel/main.c | $(BUILD)
	$(CC) $(KFLAGS) -c $< -o $@

$(OBJ_ALLOC): kernel/alloc.c | $(BUILD)
	$(CC) $(KFLAGS) -c $< -o $@

# ── font renderer (stb_truetype, SSE ok for float ABI) ───────────────────────
$(OBJ_FONT): drivers/font.c | $(BUILD)
	$(CC) $(KFLAGS) $(FONT_EXTRA) -I$(STB_DIR) -c $< -o $@

# ── platform drivers ──────────────────────────────────────────────────────────
$(OBJ_SERIAL):   drivers/serial.c   | $(BUILD)
	$(CC) $(KFLAGS) -c $< -o $@

$(OBJ_KEYBOARD): drivers/keyboard.c | $(BUILD)
	$(CC) $(KFLAGS) -c $< -o $@

$(OBJ_TERMINAL): drivers/terminal.c | $(BUILD)
	$(CC) $(KFLAGS) -c $< -o $@

# ── SMP + PCI (arch/x86) ──────────────────────────────────────────────────────
$(OBJ_SMP): arch/x86/smp.c | $(BUILD)
	$(CC) $(KFLAGS) -c $< -o $@

$(OBJ_PCI): arch/x86/pci.c | $(BUILD)
	$(CC) $(KFLAGS) -c $< -o $@

$(OBJ_VM): arch/x86/vm.c | $(BUILD)
	$(CC) $(KFLAGS) -c $< -o $@

# ── network drivers ───────────────────────────────────────────────────────────
$(OBJ_NET):     drivers/net/net.c        | $(BUILD)
	$(CC) $(KFLAGS) -c $< -o $@

$(OBJ_E1000):   drivers/net/e1000.c     | $(BUILD)
	$(CC) $(KFLAGS) -c $< -o $@

$(OBJ_E1000E):  drivers/net/e1000e.c    | $(BUILD)
	$(CC) $(KFLAGS) -c $< -o $@

$(OBJ_VIRTIO):  drivers/net/virtio_net.c | $(BUILD)
	$(CC) $(KFLAGS) -c $< -o $@

$(OBJ_RTL8139): drivers/net/rtl8139.c   | $(BUILD)
	$(CC) $(KFLAGS) -c $< -o $@

$(OBJ_PCNET):   drivers/net/pcnet.c     | $(BUILD)
	$(CC) $(KFLAGS) -c $< -o $@

$(OBJ_NE2K):    drivers/net/ne2k.c      | $(BUILD)
	$(CC) $(KFLAGS) -c $< -o $@

# iwlwifi compilation — explicit header deps because the project doesn't
# auto-generate .d files; otherwise edits to iwl_csr.h / iwl_ctxt.h /
# iwl_fw.h don't trigger rebuilds.
IWL_HDRS := drivers/net/iwlwifi/iwl_csr.h \
            drivers/net/iwlwifi/iwl_ctxt.h \
            drivers/net/iwlwifi/iwl_fw.h \
            drivers/net/iwlwifi/iwl_cmd.h \
            drivers/net/iwlwifi/iwlwifi.h

$(OBJ_IWLWIFI): drivers/net/iwlwifi/iwlwifi.c $(IWL_HDRS) | $(BUILD)
	$(CC) $(KFLAGS) -c $< -o $@

$(OBJ_IWL_FW_LDR): drivers/net/iwlwifi/iwl_fw.c $(IWL_HDRS) | $(BUILD)
	$(CC) $(KFLAGS) -c $< -o $@

$(OBJ_IWL_FW_BOOT): drivers/net/iwlwifi/iwl_fw_load.c $(IWL_HDRS) | $(BUILD)
	$(CC) $(KFLAGS) -c $< -o $@

$(OBJ_IWL_CMD): drivers/net/iwlwifi/iwl_cmd.c $(IWL_HDRS) | $(BUILD)
	$(CC) $(KFLAGS) -c $< -o $@

$(OBJ_ARP):     drivers/net/arp.c       | $(BUILD)
	$(CC) $(KFLAGS) -c $< -o $@

$(OBJ_IPV4):    drivers/net/ipv4.c      | $(BUILD)
	$(CC) $(KFLAGS) -c $< -o $@

$(OBJ_DHCP):    drivers/net/dhcp.c      | $(BUILD)
	$(CC) $(KFLAGS) -c $< -o $@

$(OBJ_TCP):     drivers/net/tcp.c       | $(BUILD)
	$(CC) $(KFLAGS) -c $< -o $@

$(OBJ_HTTP):    drivers/net/http.c      | $(BUILD)
	$(CC) $(KFLAGS) -c $< -o $@

# ── video drivers ─────────────────────────────────────────────────────────────
$(OBJ_VIDEO):   drivers/video/video.c      | $(BUILD)
	$(CC) $(KFLAGS) -c $< -o $@

$(OBJ_BGA):     drivers/video/bga.c        | $(BUILD)
	$(CC) $(KFLAGS) -c $< -o $@

$(OBJ_VGPU):    drivers/video/virtio_gpu.c | $(BUILD)
	$(CC) $(KFLAGS) -c $< -o $@

$(OBJ_LIMINEFB): drivers/video/limine_fb.c | $(BUILD)
	$(CC) $(KFLAGS) -c $< -o $@

# ── audio drivers ─────────────────────────────────────────────────────────────
$(OBJ_AUDIO):   drivers/audio/audio.c      | $(BUILD)
	$(CC) $(KFLAGS) -c $< -o $@

$(OBJ_HDA):     drivers/audio/hda.c        | $(BUILD)
	$(CC) $(KFLAGS) -c $< -o $@

$(OBJ_AC97):    drivers/audio/ac97.c       | $(BUILD)
	$(CC) $(KFLAGS) -c $< -o $@

$(OBJ_PCSPK):   drivers/audio/pcspk.c      | $(BUILD)
	$(CC) $(KFLAGS) -c $< -o $@

# ── input drivers ─────────────────────────────────────────────────────────────
$(OBJ_MOUSE): drivers/mouse.c | $(BUILD)
	$(CC) $(KFLAGS) -c $< -o $@

$(OBJ_SAM): drivers/sam/sam.c | $(BUILD)
	$(CC) $(KFLAGS) -c $< -o $@

$(OBJ_VIRTIO_INPUT): drivers/virtio_input.c | $(BUILD)
	$(CC) $(KFLAGS) -c $< -o $@

# ── shell + apps ──────────────────────────────────────────────────────────────
$(OBJ_SHELL): apps/shell/shell.c | $(BUILD)
	$(CC) $(KFLAGS) -c $< -o $@

$(OBJ_RAYTRACE): apps/raytrace/raytrace.c | $(BUILD)
	$(CC) $(KFLAGS) -c $< -o $@

$(OBJ_PIANO): apps/piano/piano.c | $(BUILD)
	$(CC) $(KFLAGS) -c $< -o $@

# ── Piano sample generation and embedding ─────────────────────────────────────
# tools/gen_samples is compiled from C and run once to produce the .raw files.
# Each .raw is then embedded as a binary ELF object via objcopy.

tools/gen_samples: tools/gen_samples.c
	gcc -O2 -o $@ $< -lm

$(SAMPLE_RAWS): tools/gen_samples
	@mkdir -p samples
	tools/gen_samples

$(BUILD)/sample_piano_%.o: samples/piano_%.raw | $(BUILD)
	$(OBJCOPY) \
	    -I binary \
	    -O elf64-x86-64 \
	    -B i386:x86-64 \
	    $< $@

# ── embedded TTF font ─────────────────────────────────────────────────────────
$(OBJ_FONT_TTF): $(FONT_TTF) | $(BUILD)
	$(OBJCOPY) \
	    -I binary \
	    -O elf64-x86-64 \
	    -B i386:x86-64 \
	    $< $@

# ── link ──────────────────────────────────────────────────────────────────────
$(KERNEL_ELF): $(OBJS) kernel/linker.ld
	$(LD) $(LDFLAGS) $(OBJS) -o $@

# ── ISO ───────────────────────────────────────────────────────────────────────
iso: $(KERNEL_ELF)
	@mkdir -p $(ISO_ROOT)/boot/limine
	@mkdir -p $(ISO_ROOT)/EFI/BOOT
	cp $(KERNEL_ELF)                    $(ISO_ROOT)/kernel.elf
	cp boot/limine.conf                 $(ISO_ROOT)/boot/limine/limine.conf
	cp $(LIMINE_DIR)/limine-bios.sys    $(ISO_ROOT)/boot/limine/
	cp $(LIMINE_DIR)/limine-bios-cd.bin $(ISO_ROOT)/boot/limine/
	cp $(LIMINE_DIR)/limine-uefi-cd.bin $(ISO_ROOT)/boot/limine/
	cp $(LIMINE_DIR)/BOOTX64.EFI        $(ISO_ROOT)/EFI/BOOT/
	@if [ -f "$(IWL_FW_BIN)" ]; then                           \
	    cp "$(IWL_FW_BIN)" $(ISO_ROOT)/iwlwifi.ucode;          \
	    echo "  bundled $(IWL_FW_BIN)";                        \
	fi
	xorriso -as mkisofs \
	    -b boot/limine/limine-bios-cd.bin \
	    -no-emul-boot \
	    -boot-load-size 4 \
	    -boot-info-table \
	    --efi-boot boot/limine/limine-uefi-cd.bin \
	    -efi-boot-part \
	    --efi-boot-image \
	    --protective-msdos-label \
	    $(ISO_ROOT) \
	    -o $(ISO) 2>/dev/null
	$(LIMINE_DIR)/limine bios-install $(ISO)
	@echo "ISO ready: $(ISO)"

# ── Run in QEMU ───────────────────────────────────────────────────────────────
QEMU   := qemu-system-x86_64
OVMF   := /usr/share/ovmf/OVMF.fd
NIC    ?= e1000

# Pick a host audio backend.  PulseAudio (native or via pipewire-pulse shim)
# works out of the box on virtually every desktop session, so we prefer it
# over QEMU's native pipewire driver — the latter often fails silently when
# the session bus / XDG_RUNTIME_DIR aren't set up exactly right.
# Override with:  make run AUDIODEV=pipewire   (or alsa, sdl, ...)
AUDIODEV ?= $(shell \
    if [ -S "/run/user/$$(id -u)/pulse/native" ]; then echo pa;        \
    elif [ -S "/run/user/$$(id -u)/pipewire-0" ];  then echo pipewire; \
    else echo alsa; fi)

QEMU_COMMON := \
    -machine q35 \
    -bios $(OVMF) \
    -cdrom $(ISO) \
    -m 512M \
    -smp 4 \
    -device bochs-display,xres=2560,yres=1440,vgamem=16777216 \
    -display gtk,zoom-to-fit=on \
    -serial stdio \
    -netdev user,id=net0 \
    -device $(NIC),netdev=net0 \
    -audiodev $(AUDIODEV),id=audio0 \
    -device intel-hda \
    -device hda-duplex,audiodev=audio0 \
    -device virtio-tablet-pci \
    -device virtio-keyboard-pci

KVM_FLAGS := $(shell test -w /dev/kvm && echo "-enable-kvm -cpu host" || echo "-cpu qemu64")

run: iso
	@echo "NIC: $(NIC)  (override with NIC=<device>)"
	@echo "Audio: $(AUDIODEV)  (override with AUDIODEV=<pipewire|pa|alsa|sdl|...>)"
	@echo "Tip: add yourself to the 'kvm' group for much faster execution"
	$(QEMU) $(QEMU_COMMON) $(KVM_FLAGS)

# ── Spice mode (display + audio + input over TCP) ─────────────────────────────
# For running Diamond in QEMU on a remote host over SSH.  The -audiodev pa
# path used by 'make run' pipes guest audio into the *server's* PulseAudio,
# which you can't hear from the SSH client.  Spice streams audio and video
# together over one TCP port so a local client gets both.
#
# On the server:
#    make run-spice                   # port defaults to 5930
#    make run-spice SPICE_PORT=5930
# On your local machine:
#    remote-viewer spice://<server>:5930
#    (install with:  sudo apt install virt-viewer)
SPICE_PORT ?= 5930

QEMU_SPICE := \
    -machine q35 \
    -bios $(OVMF) \
    -cdrom $(ISO) \
    -m 512M \
    -smp 4 \
    -vga qxl \
    -spice port=$(SPICE_PORT),addr=0.0.0.0,disable-ticketing=on \
    -device virtio-serial-pci \
    -chardev spicevmc,id=spicechannel0,name=vdagent \
    -device virtserialport,chardev=spicechannel0,name=com.redhat.spice.0 \
    -serial stdio \
    -netdev user,id=net0 \
    -device $(NIC),netdev=net0 \
    -audiodev spice,id=audio0 \
    -device intel-hda \
    -device hda-duplex,audiodev=audio0

run-spice: iso
	@echo "Spice listening on 0.0.0.0:$(SPICE_PORT)"
	@echo "Connect from your local machine: remote-viewer spice://<this-host>:$(SPICE_PORT)"
	$(QEMU) $(QEMU_SPICE) $(KVM_FLAGS)

# ── Install to EFI partition (dual-boot alongside Linux) ─────────────────────
# Copies kernel.elf + Limine EFI binary + config to /boot/efi/EFI/diamond/.
# Run once: make efi-register   to add the UEFI boot entry via efibootmgr.
# Subsequently: make install    to update the kernel after rebuilding.
EFI_DIR := /boot/efi/EFI/diamond

install: $(KERNEL_ELF)
	@echo "Installing Diamond to $(EFI_DIR) ..."
	sudo mkdir -p $(EFI_DIR)
	sudo mkdir -p /boot/efi/boot/limine
	sudo cp $(KERNEL_ELF)                    $(EFI_DIR)/kernel.elf
	sudo cp $(LIMINE_DIR)/BOOTX64.EFI        $(EFI_DIR)/limine.efi
	sudo cp boot/limine-efi.conf             $(EFI_DIR)/limine.conf
	sudo cp boot/limine-efi.conf             /boot/efi/boot/limine/limine.conf
	@if [ -f "$(IWL_FW_BIN)" ]; then                          \
	    echo "  bundling iwlwifi firmware ..."; \
	    sudo cp "$(IWL_FW_BIN)" $(EFI_DIR)/iwlwifi.ucode;     \
	fi
	@echo "Done. Run 'make efi-register' once to add the UEFI boot entry."

# Run this once to register Diamond in the UEFI boot menu.
# Find the EFI partition disk/part with: lsblk -o NAME,FSTYPE,MOUNTPOINT
efi-register:
	@PART_DEV=$$(findmnt -n -o SOURCE /boot/efi) && \
	 DISK=$$(lsblk -no PKNAME $$PART_DEV) && \
	 PART=$$(cat /sys/class/block/$$(basename $$PART_DEV)/partition) && \
	 echo "Registering Diamond on /dev/$$DISK partition $$PART ..." && \
	 sudo efibootmgr --create \
	     --disk /dev/$$DISK \
	     --part $$PART \
	     --label "Diamond" \
	     --loader '\EFI\diamond\limine.efi' \
	     --unicode && \
	 echo "Boot entry created. Current boot order:" && \
	 sudo efibootmgr

# ── Clean ─────────────────────────────────────────────────────────────────────
clean:
	rm -rf $(BUILD) $(ISO)

$(BUILD):
	mkdir -p $(BUILD)
