timeout: 5

/Ubuntu (grub)
    protocol: efi_chainload
    image_path: boot():/EFI/ubuntu/grubx64.efi

/Diamond
    protocol: limine
    path: boot():/EFI/diamond/kernel.elf
    framebuffer_width: 2256
    framebuffer_height: 1504
    framebuffer_bpp: 32
    module_path: boot():/EFI/diamond/iwlwifi.ucode
    module_cmdline: iwlwifi

/Ubuntu (shim)
    protocol: efi_chainload
    image_path: boot():/EFI/ubuntu/shimx64.efi

