timeout: 0

/Diamond
    protocol: limine
    path: boot():/kernel.elf
    framebuffer_width: 1920
    framebuffer_height: 1080
    framebuffer_bpp: 32
    module_path: boot():/iwlwifi.ucode
    module_cmdline: iwlwifi
