/*
 * piano.c — 88-key interactive piano demo.
 *
 * Renders a full-width 88-key piano at the bottom of the framebuffer.
 * Mouse movement updates a crosshair cursor.  Left-click on a key highlights
 * it and plays the corresponding pitch-shifted sample through audio_play_pcm.
 *
 * Samples (A1–A6, 44100 Hz mono 16-bit) are generated at build time by
 * tools/gen_samples and embedded via objcopy.  Playback pitch-shifts the
 * nearest anchor note to reach any of the 88 keys.
 *
 * Key layout (MIDI 21 = A0 … 108 = C8):
 *   52 white keys × s_wkw pixels wide, s_wkh pixels tall.
 *   36 black keys overlaid in the upper s_bkh portion.
 *
 * Exit: press ESC or Q.
 */

#include <stdint.h>
#include "piano.h"
#include "../../drivers/video/video.h"
#include "../../drivers/audio/audio.h"
#include "../../drivers/keyboard.h"
#include "../../drivers/mouse.h"
#include "../../drivers/virtio_input.h"   /* virtio_input_has_tablet() */

/* ── Piano geometry ──────────────────────────────────────────────────────── */

#define NUM_WHITE_KEYS   52
#define PIANO_FRAC_H      5   /* piano height = screen_height / PIANO_FRAC_H */
#define BLACK_KEY_H_FRAC 62   /* black key height as % of white key height   */
#define BLACK_KEY_W_FRAC 55   /* black key width  as % of white key width    */

/* ── Colours (0x00RRGGBB) ────────────────────────────────────────────────── */

#define COL_BG        0x1A1A2Eu
#define COL_WHITE_KEY 0xF5F5F5u
#define COL_WHITE_LIT 0x88CCFFu
#define COL_WHITE_BDR 0x555555u
#define COL_BLACK_KEY 0x1C1C1Cu
#define COL_BLACK_LIT 0x2266AAu
#define COL_CURSOR    0xFFFFFFu

/* ── Key tables ──────────────────────────────────────────────────────────── */

/* MIDI note for each of the 52 white keys (A0…C8). */
static const uint8_t s_white_midi[52] = {
    21, 23,
    24, 26, 28, 29, 31, 33, 35,
    36, 38, 40, 41, 43, 45, 47,
    48, 50, 52, 53, 55, 57, 59,
    60, 62, 64, 65, 67, 69, 71,
    72, 74, 76, 77, 79, 81, 83,
    84, 86, 88, 89, 91, 93, 95,
    96, 98,100,101,103,105,107,
   108
};

/* Black keys: {left-white-key-index, MIDI note}. */
static const uint8_t s_black[36][2] = {
    {  0, 22 },
    {  2, 25 }, {  3, 27 }, {  5, 30 }, {  6, 32 }, {  7, 34 },
    {  9, 37 }, { 10, 39 }, { 12, 42 }, { 13, 44 }, { 14, 46 },
    { 16, 49 }, { 17, 51 }, { 19, 54 }, { 20, 56 }, { 21, 58 },
    { 23, 61 }, { 24, 63 }, { 26, 66 }, { 27, 68 }, { 28, 70 },
    { 30, 73 }, { 31, 75 }, { 33, 78 }, { 34, 80 }, { 35, 82 },
    { 37, 85 }, { 38, 87 }, { 40, 90 }, { 41, 92 }, { 42, 94 },
    { 44, 97 }, { 45, 99 }, { 47,102 }, { 48,104 }, { 49,106 },
};

/* ── Embedded samples ────────────────────────────────────────────────────── */
/*
 * Six anchor notes (A1–A6), generated by tools/gen_samples and linked in
 * as binary objects by the Makefile.  Format: 44100 Hz, s16le, mono.
 */

#define NUM_SAMPLES 6

extern const int16_t _binary_samples_piano_A1_raw_start[];
extern const int16_t _binary_samples_piano_A1_raw_end[];
extern const int16_t _binary_samples_piano_A2_raw_start[];
extern const int16_t _binary_samples_piano_A2_raw_end[];
extern const int16_t _binary_samples_piano_A3_raw_start[];
extern const int16_t _binary_samples_piano_A3_raw_end[];
extern const int16_t _binary_samples_piano_A4_raw_start[];
extern const int16_t _binary_samples_piano_A4_raw_end[];
extern const int16_t _binary_samples_piano_A5_raw_start[];
extern const int16_t _binary_samples_piano_A5_raw_end[];
extern const int16_t _binary_samples_piano_A6_raw_start[];
extern const int16_t _binary_samples_piano_A6_raw_end[];

static const int16_t *const s_smp_data[NUM_SAMPLES] = {
    _binary_samples_piano_A1_raw_start,
    _binary_samples_piano_A2_raw_start,
    _binary_samples_piano_A3_raw_start,
    _binary_samples_piano_A4_raw_start,
    _binary_samples_piano_A5_raw_start,
    _binary_samples_piano_A6_raw_start,
};
static const int16_t *const s_smp_end[NUM_SAMPLES] = {
    _binary_samples_piano_A1_raw_end,
    _binary_samples_piano_A2_raw_end,
    _binary_samples_piano_A3_raw_end,
    _binary_samples_piano_A4_raw_end,
    _binary_samples_piano_A5_raw_end,
    _binary_samples_piano_A6_raw_end,
};

/* MIDI root note of each anchor sample. */
static const int s_smp_midi[NUM_SAMPLES] = { 33, 45, 57, 69, 81, 93 };

/*
 * Pitch-shift ratios in Q16.16 for −12 … +12 semitones.
 * ratio = 2^(semitones/12) × 65536.
 * Advancing source by ratio per output frame raises pitch; fewer output
 * frames result (note is shorter but higher, matching a real piano).
 */
static const uint32_t s_pitch_q16[25] = {
    32768, 34716, 36784, 38968, 41285, 43748, 46341, 49096, 52016,
    55109, 58386, 61857,
    65536,   /* 0 semitones — identity */
    69433, 73562, 77936, 82570, 87480, 92682, 98193,104032,110218,
   116772,123713,131072,
};

#define DMA_FRAMES 4096u

static int16_t s_pcm_buf[DMA_FRAMES * 2u];   /* stereo interleaved */

/* ── Cursor ──────────────────────────────────────────────────────────────── */

#define CUR_R      10
#define CUR_SAVE_SZ (2 * (CUR_R + 1))   /* 22 — fits ±10 px in each axis */

static uint32_t s_cur_save[CUR_SAVE_SZ * CUR_SAVE_SZ];
static int32_t  s_cur_x, s_cur_y;

static void cur_save(uint32_t *fb, int32_t sw, int32_t sh, int32_t cx, int32_t cy) {
    int r = CUR_R;
    for (int dy = -r; dy <= r; dy++) {
        for (int dx = -r; dx <= r; dx++) {
            int px = cx + dx, py = cy + dy;
            uint32_t v = 0u;
            if (px >= 0 && px < sw && py >= 0 && py < sh)
                v = fb[(uint32_t)py * (uint32_t)sw + (uint32_t)px];
            s_cur_save[(dy + r) * CUR_SAVE_SZ + (dx + r)] = v;
        }
    }
}

static void cur_restore(uint32_t *fb, int32_t sw, int32_t sh, int32_t cx, int32_t cy) {
    int r = CUR_R;
    for (int dy = -r; dy <= r; dy++) {
        for (int dx = -r; dx <= r; dx++) {
            int px = cx + dx, py = cy + dy;
            if (px >= 0 && px < sw && py >= 0 && py < sh)
                fb[(uint32_t)py * (uint32_t)sw + (uint32_t)px] =
                    s_cur_save[(dy + r) * CUR_SAVE_SZ + (dx + r)];
        }
    }
}

static void cur_draw(uint32_t *fb, int32_t sw, int32_t sh, int32_t cx, int32_t cy) {
    for (int dx = -CUR_R; dx <= CUR_R; dx++) {
        int px = cx + dx;
        if (px >= 0 && px < sw && cy >= 0 && cy < sh)
            fb[(uint32_t)cy * (uint32_t)sw + (uint32_t)px] = COL_CURSOR;
    }
    for (int dy = -CUR_R; dy <= CUR_R; dy++) {
        int py = cy + dy;
        if (cx >= 0 && cx < sw && py >= 0 && py < sh)
            fb[(uint32_t)py * (uint32_t)sw + (uint32_t)cx] = COL_CURSOR;
    }
    for (int dy = -1; dy <= 1; dy++)
        for (int dx = -1; dx <= 1; dx++) {
            int px = cx + dx, py = cy + dy;
            if (px >= 0 && px < sw && py >= 0 && py < sh)
                fb[(uint32_t)py * (uint32_t)sw + (uint32_t)px] = 0xFF4444u;
        }
}

/*
 * Play the pitch-shifted note for MIDI key `midi` in DMA_FRAMES chunks
 * for as long as the space bar is held.  The sample loops back to the
 * beginning when exhausted so the note sustains indefinitely.
 * Between DMA chunks the cursor position is updated so the display stays
 * responsive even during playback.
 */
static void play_note_while_held(int midi, uint32_t *fb,
                                  int32_t sw, int32_t sh) {
    /* Find nearest anchor sample. */
    int best = 0, best_dist = 1000;
    for (int i = 0; i < NUM_SAMPLES; i++) {
        int d = midi - s_smp_midi[i];
        if (d < 0) d = -d;
        if (d < best_dist) { best_dist = d; best = i; }
    }
    int semidiff = midi - s_smp_midi[best];
    if (semidiff < -12) semidiff = -12;
    if (semidiff >  12) semidiff =  12;
    uint32_t ratio      = s_pitch_q16[semidiff + 12];
    const int16_t *src  = s_smp_data[best];
    uint32_t src_frames = (uint32_t)(s_smp_end[best] - src);
    uint32_t src_q16    = 0u;

    /* Loop: fill one DMA chunk then hand it to the audio driver.
     * kb_space_held() drains keyboard hardware between chunks. */
    while (kb_space_held()) {
        for (uint32_t i = 0u; i < DMA_FRAMES; i++) {
            if ((src_q16 >> 16) >= src_frames)
                src_q16 = 0u;          /* loop sample */
            int16_t v = src[src_q16 >> 16];
            s_pcm_buf[i * 2u]      = v;
            s_pcm_buf[i * 2u + 1u] = v;
            src_q16 += ratio;
        }
        audio_play_pcm(s_pcm_buf, DMA_FRAMES, 44100u);

        /* Update cursor between DMA chunks (~93 ms each). */
        int32_t nx, ny; uint8_t nb;
        if (mouse_poll(&nx, &ny, &nb)) {
            cur_restore(fb, sw, sh, s_cur_x, s_cur_y);
            s_cur_x = nx; s_cur_y = ny;
            cur_save(fb, sw, sh, s_cur_x, s_cur_y);
            cur_draw(fb, sw, sh, s_cur_x, s_cur_y);
        }
    }
}

/* ── Piano rendering ─────────────────────────────────────────────────────── */

static int32_t s_px, s_py, s_wkw, s_wkh, s_bkw, s_bkh;

static void piano_init_geom(uint32_t sw, uint32_t sh) {
    s_wkh = (int32_t)(sh / (uint32_t)PIANO_FRAC_H);
    s_wkw = (int32_t)(sw / NUM_WHITE_KEYS);
    s_px  = (int32_t)((sw - (uint32_t)(s_wkw * NUM_WHITE_KEYS)) / 2u);
    s_py  = (int32_t)sh - s_wkh;
    s_bkh = s_wkh * BLACK_KEY_H_FRAC / 100;
    s_bkw = s_wkw * BLACK_KEY_W_FRAC / 100;
    if (s_bkw < 4) s_bkw = 4;
}

static void draw_white(int wi, uint32_t col) {
    int x = (int)(s_px + wi * s_wkw);
    video_rect(x + 1, (int)s_py + 1, (int)s_wkw - 2, (int)s_wkh - 2, col);
    video_rect_border(x, (int)s_py, (int)s_wkw, (int)s_wkh, COL_WHITE_BDR);
}

static void draw_black(int bi, uint32_t col) {
    int lw = (int)s_black[bi][0];
    int bx = (int)s_px + (lw + 1) * (int)s_wkw - (int)s_bkw / 2;
    video_rect(bx, (int)s_py, (int)s_bkw, (int)s_bkh, col);
    video_hline(bx + 1, (int)s_py + 1, (int)s_bkw - 2, 0x444444u);
}

static void piano_draw(void) {
    video_rect((int)s_px, (int)s_py, NUM_WHITE_KEYS * (int)s_wkw, (int)s_wkh, COL_BG);
    for (int i = 0; i < NUM_WHITE_KEYS; i++) draw_white(i, COL_WHITE_KEY);
    for (int i = 0; i < 36; i++)            draw_black(i, COL_BLACK_KEY);
}

static void key_set(int midi, int pressed) {
    for (int i = 0; i < 36; i++) {
        if ((int)s_black[i][1] == midi) {
            draw_black(i, pressed ? COL_BLACK_LIT : COL_BLACK_KEY);
            return;
        }
    }
    for (int i = 0; i < NUM_WHITE_KEYS; i++) {
        if ((int)s_white_midi[i] == midi) {
            draw_white(i, pressed ? COL_WHITE_LIT : COL_WHITE_KEY);
            for (int j = 0; j < 36; j++) {
                int lw = (int)s_black[j][0];
                if (lw == i - 1 || lw == i)
                    draw_black(j, COL_BLACK_KEY);
            }
            return;
        }
    }
}

/* ── Hit testing ─────────────────────────────────────────────────────────── */

static int piano_hit(int32_t mx, int32_t my) {
    if (my < s_py) return -1;
    int ly = (int)(my - s_py);
    if (ly >= (int)s_wkh) return -1;
    if (ly < (int)s_bkh) {
        for (int i = 0; i < 36; i++) {
            int lw = (int)s_black[i][0];
            int bx = (int)s_px + (lw + 1) * (int)s_wkw - (int)s_bkw / 2;
            if (mx >= bx && mx < bx + (int)s_bkw) return (int)s_black[i][1];
        }
    }
    int lx = (int)(mx - s_px);
    if (lx < 0) return -1;
    int wi = lx / (int)s_wkw;
    if (wi >= NUM_WHITE_KEYS) return -1;
    return (int)s_white_midi[wi];
}

/* ── Main entry ──────────────────────────────────────────────────────────── */

void piano_run(void) {
    uint32_t sw = video_width(), sh = video_height();
    uint32_t *fb = (uint32_t *)video_framebuffer();
    int32_t  isw = (int32_t)sw, ish = (int32_t)sh;

    piano_init_geom(sw, sh);
    if (!virtio_input_has_tablet())
        mouse_init(sw, sh);

    video_clear(COL_BG);
    piano_draw();

    s_cur_x = (int32_t)(sw / 2u);
    s_cur_y = s_py - (int32_t)(sh / 10u);
    if (s_cur_y < 0) s_cur_y = 0;

    /* Drain stale mouse events so cursor jumps to the real position. */
    {
        int32_t ix, iy; uint8_t ib = 0;
        while (mouse_poll(&ix, &iy, &ib)) { s_cur_x = ix; s_cur_y = iy; }
    }
    cur_save(fb, isw, ish, s_cur_x, s_cur_y);
    cur_draw(fb, isw, ish, s_cur_x, s_cur_y);

    int hover_midi = -1;   /* piano key the cursor is over, or -1 */

    for (;;) {
        /* ── keyboard ──────────────────────────────────────────────── */
        int ch = kb_getchar();
        if (ch == 27 || ch == 'q' || ch == 'Q') break;

        if (ch == ' ' && hover_midi >= 0) {
            /* Space pressed over a key → play until space is released. */
            play_note_while_held(hover_midi, fb, isw, ish);

            /* Cursor may have moved during playback; re-sync hover state. */
            cur_restore(fb, isw, ish, s_cur_x, s_cur_y);
            if (hover_midi >= 0) { key_set(hover_midi, 0); hover_midi = -1; }
            int nh = piano_hit(s_cur_x, s_cur_y);
            if (nh >= 0) { key_set(nh, 1); hover_midi = nh; }
            cur_save(fb, isw, ish, s_cur_x, s_cur_y);
            cur_draw(fb, isw, ish, s_cur_x, s_cur_y);
        }

        /* ── mouse ─────────────────────────────────────────────────── */
        int32_t nx, ny; uint8_t btns;
        if (mouse_poll(&nx, &ny, &btns)) {
            cur_restore(fb, isw, ish, s_cur_x, s_cur_y);

            /* Highlight whichever key the cursor is now over. */
            int new_hover = piano_hit(nx, ny);
            if (new_hover != hover_midi) {
                if (hover_midi >= 0) key_set(hover_midi, 0);
                hover_midi = new_hover;
                if (hover_midi >= 0) key_set(hover_midi, 1);
            }

            s_cur_x = nx; s_cur_y = ny;
            cur_save(fb, isw, ish, s_cur_x, s_cur_y);
            cur_draw(fb, isw, ish, s_cur_x, s_cur_y);
        }

        __asm__ volatile ("pause");
    }

    /* Clean up */
    cur_restore(fb, isw, ish, s_cur_x, s_cur_y);
    if (hover_midi >= 0) key_set(hover_midi, 0);
    video_clear(0x000000u);
}
